#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import syd
import click
from PySide2.QtWidgets import QApplication
from ui import SydMainWindow

# -----------------------------------------------------------------------------
CONTEXT_SETTINGS = dict(help_option_names=['-h', '--help'])


@click.command(context_settings=CONTEXT_SETTINGS)
@click.option('--db', default='',
              help='DB filename (SYD_DB_FILENAME environment variable is used if no filename)')
@syd.add_options(syd.common_options)
def syd_ui(db, **kwargs):
    syd.logging_conf(**kwargs)

    db_filename = syd.get_db_filename(db)

    app = QApplication(sys.argv)
    m = SydMainWindow()
    m.set_database(db_filename)
    m.slot_on_load_new_table('Patient')
    m.show()
    app.exec_()


if __name__ == '__main__':
    syd_ui()
